repos:
  - repo: local
    hooks:
      - id: deadnix
        name: deadnix
        entry: deadnix --edit
        language: system
        types: [nix]

      - id: statix
        name: statix
        entry: statix check
        language: system
        types: [nix]
        pass_filenames: false

      - id: nixfmt
        name: nixfmt
        entry: nixfmt
        language: system
        types: [nix]

      - id: nix-flake-check
        name: nix flake check
        entry: nix flake check
        language: system
        pass_filenames: false
        types: [nix]
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
