let
  # SSH public keys for encryption
  # These should be the public keys corresponding to the SSH keys managed by 1Password
  users = {
    ungood = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEdPl6iM2IJglLSUcpgJJH9uEnHjxVuxm11eRdDHdq2G test@example.com";
    trafficcone = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEdPl6iM2IJglLSUcpgJJH9uEnHjxVuxm11eRdDHdq2G test@example.com";
  };

  # Host SSH keys (these will be auto-generated by NixOS)
  hosts = {
    sparrowhawk = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEdPl6iM2IJglLSUcpgJJH9uEnHjxVuxm11eRdDHdq2G test@example.com";
  };

  # All authorized keys (users + hosts)
  allKeys = builtins.attrValues users ++ builtins.attrValues hosts;
in
{
  # User password secrets
  "ungood-password.age".publicKeys = allKeys;
  "trafficcone-password.age".publicKeys = allKeys;
}
